# This is  Thoth's configuration file placed in a root of a repo
# (named as .thoth.yaml) used by Thamos CLI as well as by Thoth bots. Please
# adjust values listed below as desired.

host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: fedora:34
    operating_system:
      name: fedora 
      version: '34'
    python_version: '3.8'
    recommendation_type: stable
    platform: linux-x86_64

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - sesheta
        - goern
      assignees:
        - sesehta 
      labels:
        - bot
      changelog_file: true
      changelog_smart: true
